//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_Server_Manager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minecraft_Server_Manager.de_local", typeof(de_local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abenteuer.
        /// </summary>
        internal static string Adventure {
            get {
                return ResourceManager.GetString("Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Befehl.
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreativ.
        /// </summary>
        internal static string Creative {
            get {
                return ResourceManager.GetString("Creative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuell.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server löschen.
        /// </summary>
        internal static string DeleteServer {
            get {
                return ResourceManager.GetString("DeleteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Download ist abgeschlossen.
        ///
        ///Willst du das Update jetzt installieren?.
        /// </summary>
        internal static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoriten.
        /// </summary>
        internal static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoriten.
        /// </summary>
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installiere.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damit die eben installierten Schriftarten genutzt werden können, muss das Programm neugestartet werden. 
        ///
        ///Jetzt neustarten?.
        /// </summary>
        internal static string InstalledFonts {
            get {
                return ResourceManager.GetString("InstalledFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kicke.
        /// </summary>
        internal static string Kick {
            get {
                return ResourceManager.GetString("Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menü.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modus.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuste.
        /// </summary>
        internal static string Newest {
            get {
                return ResourceManager.GetString("Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht Neustarten.
        /// </summary>
        internal static string NoRestart {
            get {
                return ResourceManager.GetString("NoRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vom Server..
        /// </summary>
        internal static string of_the_server {
            get {
                return ResourceManager.GetString("of_the_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfad.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spieler.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen zurücksetzen.
        /// </summary>
        internal static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neustarten.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um die geänderten Spracheinstellungen anzuwenden muss das Programm neugestartet werden.
        ///
        ///Jetzt neustarten?.
        /// </summary>
        internal static string Restart_Language {
            get {
                return ResourceManager.GetString("Restart_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speicher.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisch nach Updates suchen.
        /// </summary>
        internal static string SearchForUpdates {
            get {
                return ResourceManager.GetString("SearchForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server lädt ....
        /// </summary>
        internal static string Server_Loading {
            get {
                return ResourceManager.GetString("Server_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online auf.
        /// </summary>
        internal static string Server_Online {
            get {
                return ResourceManager.GetString("Server_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server fährt herunter ....
        /// </summary>
        internal static string Server_Shutdown {
            get {
                return ResourceManager.GetString("Server_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server gestartet ....
        /// </summary>
        internal static string Server_Started {
            get {
                return ResourceManager.GetString("Server_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Servers {
            get {
                return ResourceManager.GetString("Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setzte den Spielmodus von.
        /// </summary>
        internal static string Set_GameMode {
            get {
                return ResourceManager.GetString("Set_GameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige Kurzinfos (Tooltips).
        /// </summary>
        internal static string Show_ToolTips {
            get {
                return ResourceManager.GetString("Show_ToolTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um die geänderten Kurzinfoeinstellungen anzuwenden muss das Programm neugestartet werden.
        ///
        ///Jetzt neustarten?.
        /// </summary>
        internal static string Show_ToolTips_Changed {
            get {
                return ResourceManager.GetString("Show_ToolTips_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige Java Server UI.
        /// </summary>
        internal static string ShowUI {
            get {
                return ResourceManager.GetString("ShowUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuschauer.
        /// </summary>
        internal static string Spectator {
            get {
                return ResourceManager.GetString("Spectator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überleben.
        /// </summary>
        internal static string Survival {
            get {
                return ResourceManager.GetString("Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleporte.
        /// </summary>
        internal static string Teleport {
            get {
                return ResourceManager.GetString("Teleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auf.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zu.
        /// </summary>
        internal static string to_Player {
            get {
                return ResourceManager.GetString("to_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle den Pfad zu deinem.
        /// </summary>
        internal static string ttp_Browse {
            get {
                return ResourceManager.GetString("ttp_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Konsolenbefehl, welcher für das Starten der Server genutzt werden soll..
        /// </summary>
        internal static string ttp_CMD {
            get {
                return ResourceManager.GetString("ttp_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Ordner in welchem die Daten für das Program sind..
        /// </summary>
        internal static string ttp_DataPath {
            get {
                return ResourceManager.GetString("ttp_DataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Pfad zu der &apos;java.exe&apos; die genutzt werden soll, um die Server zu starten..
        /// </summary>
        internal static string ttp_JavaPath {
            get {
                return ResourceManager.GetString("ttp_JavaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle einen neuen.
        /// </summary>
        internal static string ttp_New {
            get {
                return ResourceManager.GetString("ttp_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das GitHub repo konnte nicht erreicht werden! Bitte überprüfe deine Internetverbindung..
        /// </summary>
        internal static string ttp_NoInternet {
            get {
                return ResourceManager.GetString("ttp_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setzte die Einstellungen auf Standardwerte zurück..
        /// </summary>
        internal static string ttp_Reset {
            get {
                return ResourceManager.GetString("ttp_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Führe den ausgewählten Befehl auf dem Server aus..
        /// </summary>
        internal static string ttp_Run {
            get {
                return ResourceManager.GetString("ttp_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Ordner in welchem deine Server sind..
        /// </summary>
        internal static string ttp_ServerPath {
            get {
                return ResourceManager.GetString("ttp_ServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte den ausgewählten Server..
        /// </summary>
        internal static string ttp_Start {
            get {
                return ResourceManager.GetString("ttp_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Update verfügbar, bitte updaten!.
        /// </summary>
        internal static string ttp_UpdateAvailable {
            get {
                return ResourceManager.GetString("ttp_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Update wurde bereits heruntergeladen, aber noch nicht installiert!
        ///
        ///Jetzt Installieren?.
        /// </summary>
        internal static string UpdateInstall {
            get {
                return ResourceManager.GetString("UpdateInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Update verfügbar!
        ///
        ///Möchtest du jetzt updaten?.
        /// </summary>
        internal static string UpdatePopUp {
            get {
                return ResourceManager.GetString("UpdatePopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
