//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_Server_Manager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minecraft_Server_Manager.en_local", typeof(en_local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        internal static string Adventure {
            get {
                return ResourceManager.GetString("Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative.
        /// </summary>
        internal static string Creative {
            get {
                return ResourceManager.GetString("Creative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Server.
        /// </summary>
        internal static string DeleteServer {
            get {
                return ResourceManager.GetString("DeleteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Download is complete!
        ///
        ///Would you like to install now?.
        /// </summary>
        internal static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use the fonts we installed just now the application has to be restarted 
        ///
        ///Restart now?.
        /// </summary>
        internal static string InstalledFonts {
            get {
                return ResourceManager.GetString("InstalledFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick.
        /// </summary>
        internal static string Kick {
            get {
                return ResourceManager.GetString("Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        internal static string Newest {
            get {
                return ResourceManager.GetString("Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Restart.
        /// </summary>
        internal static string NoRestart {
            get {
                return ResourceManager.GetString("NoRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of the server..
        /// </summary>
        internal static string of_the_server {
            get {
                return ResourceManager.GetString("of_the_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        internal static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To apply the language settings the application has to be restarted 
        ///
        ///Restart now?.
        /// </summary>
        internal static string Restart_Language {
            get {
                return ResourceManager.GetString("Restart_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically search for Updates.
        /// </summary>
        internal static string SearchForUpdates {
            get {
                return ResourceManager.GetString("SearchForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server loading ....
        /// </summary>
        internal static string Server_Loading {
            get {
                return ResourceManager.GetString("Server_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online at.
        /// </summary>
        internal static string Server_Online {
            get {
                return ResourceManager.GetString("Server_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server shutting down ....
        /// </summary>
        internal static string Server_Shutdown {
            get {
                return ResourceManager.GetString("Server_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server started ....
        /// </summary>
        internal static string Server_Started {
            get {
                return ResourceManager.GetString("Server_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        internal static string Servers {
            get {
                return ResourceManager.GetString("Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set gamemode of.
        /// </summary>
        internal static string Set_GameMode {
            get {
                return ResourceManager.GetString("Set_GameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tooltips.
        /// </summary>
        internal static string Show_ToolTips {
            get {
                return ResourceManager.GetString("Show_ToolTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To apply the tooltip settings the application has to be restarted 
        ///
        ///Restart now?.
        /// </summary>
        internal static string Show_ToolTips_Changed {
            get {
                return ResourceManager.GetString("Show_ToolTips_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Java Server UI.
        /// </summary>
        internal static string ShowUI {
            get {
                return ResourceManager.GetString("ShowUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectator.
        /// </summary>
        internal static string Spectator {
            get {
                return ResourceManager.GetString("Spectator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival.
        /// </summary>
        internal static string Survival {
            get {
                return ResourceManager.GetString("Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport.
        /// </summary>
        internal static string Teleport {
            get {
                return ResourceManager.GetString("Teleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string to_Player {
            get {
                return ResourceManager.GetString("to_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to your.
        /// </summary>
        internal static string ttp_Browse {
            get {
                return ResourceManager.GetString("ttp_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command which will be used to start your java servers..
        /// </summary>
        internal static string ttp_CMD {
            get {
                return ResourceManager.GetString("ttp_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Folder your Data for the application is stored in..
        /// </summary>
        internal static string ttp_DataPath {
            get {
                return ResourceManager.GetString("ttp_DataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the &apos;java.exe&apos; which should be used to start the servers..
        /// </summary>
        internal static string ttp_JavaPath {
            get {
                return ResourceManager.GetString("ttp_JavaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new.
        /// </summary>
        internal static string ttp_New {
            get {
                return ResourceManager.GetString("ttp_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can not reach the github repo. Please check your internet connection!.
        /// </summary>
        internal static string ttp_NoInternet {
            get {
                return ResourceManager.GetString("ttp_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your settings to the default settings..
        /// </summary>
        internal static string ttp_Reset {
            get {
                return ResourceManager.GetString("ttp_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the selected command on the server..
        /// </summary>
        internal static string ttp_Run {
            get {
                return ResourceManager.GetString("ttp_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Folder your Servers are placed in..
        /// </summary>
        internal static string ttp_ServerPath {
            get {
                return ResourceManager.GetString("ttp_ServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the selected Server..
        /// </summary>
        internal static string ttp_Start {
            get {
                return ResourceManager.GetString("ttp_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an update available, please update!.
        /// </summary>
        internal static string ttp_UpdateAvailable {
            get {
                return ResourceManager.GetString("ttp_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Update was downloaded already but not installed!
        ///
        ///Install it now?.
        /// </summary>
        internal static string UpdateInstall {
            get {
                return ResourceManager.GetString("UpdateInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an update available!
        ///
        ///Would you like to update?.
        /// </summary>
        internal static string UpdatePopUp {
            get {
                return ResourceManager.GetString("UpdatePopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
